In [4]:
import pandas as pd
import numpy as np

In [5]:
df = pd.read_csv("/Users/theerdhasjoy/BIA/ML/Dataset/train_LZdllcl.csv")
df.head(100)

    employee_id         department  ... avg_training_score is_promoted
0         65438  Sales & Marketing  ...                 49           0
1         65141         Operations  ...                 60           0
2          7513  Sales & Marketing  ...                 50           0
3          2542  Sales & Marketing  ...                 50           0
4         48945         Technology  ...                 73           0
..          ...                ...  ...                ...         ...
95        43923          Analytics  ...                 86           0
96        64109         Technology  ...                 77           0
97        41983         Operations  ...                 57           0
98        21440  Sales & Marketing  ...                 52           0
99        51256            Finance  ...                 59           0

[100 rows x 14 columns]

In [6]:
df['is_promoted'].value_counts()

is_promoted
0    50140
1     4668
Name: count, dtype: int64

In [7]:
def dataset_eda(df):

    shape_of_df = df.shape
    col_names = df.columns.tolist()
    col_dtypes = df.dtypes
    missing_val = df.isnull().sum()
    dup_val = df.duplicated().sum()
    uniq_val = df.nunique()
    stat = df.describe()

    return shape_of_df, col_names, col_dtypes, missing_val, dup_val, uniq_val, stat

dataset_eda(df)

((54808, 14),
 ['employee_id',
  'department',
  'region',
  'education',
  'gender',
  'recruitment_channel',
  'no_of_trainings',
  'age',
  'previous_year_rating',
  'length_of_service',
  'KPIs_met >80%',
  'awards_won?',
  'avg_training_score',
  'is_promoted'],
 employee_id               int64
 department                  str
 region                      str
 education                   str
 gender                      str
 recruitment_channel         str
 no_of_trainings           int64
 age                       int64
 previous_year_rating    float64
 length_of_service         int64
 KPIs_met >80%             int64
 awards_won?               int64
 avg_training_score        int64
 is_promoted               int64
 dtype: object,
 employee_id                0
 department                 0
 region                     0
 education               2409
 gender                     0
 recruitment_channel        0
 no_of_trainings            0
 age                        0
 previous_year_rating    4124
 length_of_service          0
 KPIs_met >80%              0
 awards_won?                0
 avg_training_score         0
 is_promoted                0
 dtype: int64,
 np.int64(0),
 employee_id             54808
 department                  9
 region                     34
 education                   3
 gender                      2
 recruitment_channel         3
 no_of_trainings            10
 age                        41
 previous_year_rating        5
 length_of_service          35
 KPIs_met >80%               2
 awards_won?                 2
 avg_training_score         61
 is_promoted                 2
 dtype: int64,
         employee_id  no_of_trainings  ...  avg_training_score   is_promoted
 count  54808.000000     54808.000000  ...        54808.000000  54808.000000
 mean   39195.830627         1.253011  ...           63.386750      0.085170
 std    22586.581449         0.609264  ...           13.371559      0.279137
 min        1.000000         1.000000  ...           39.000000      0.000000
 25%    19669.750000         1.000000  ...           51.000000      0.000000
 50%    39225.500000         1.000000  ...           60.000000      0.000000
 75%    58730.500000         1.000000  ...           76.000000      0.000000
 max    78298.000000        10.000000  ...           99.000000      1.000000

 [8 rows x 9 columns])

In [8]:
df.columns.tolist()

['employee_id',
 'department',
 'region',
 'education',
 'gender',
 'recruitment_channel',
 'no_of_trainings',
 'age',
 'previous_year_rating',
 'length_of_service',
 'KPIs_met >80%',
 'awards_won?',
 'avg_training_score',
 'is_promoted']

In [9]:
target = 'is_promoted'

In [10]:
def feat_engg(df, num_cols, cat_cols):

    for col in num_cols:
        if df[col].isnull().sum() > 0:
            df[col] = df[col].fillna(df[col].mean())

    for col in cat_cols:
        if df[col].isnull().sum() > 0:
            df[col] = df[col].fillna(df[col].mode()[0])


    for col in num_cols:
        Q1 = df[col].quantile(0.25)
        Q3 = df[col].quantile(0.75)

        IQR = Q3 - Q1

        lower = Q1 - 1.5 * IQR
        upper = Q3 + 1.5 * IQR

        outliers = (df[col] < lower) | (df[col] > upper)

        no_of_out = outliers.sum()

        df[col] = df[col].clip(lower, upper)

    return df

cat_cols = df.select_dtypes(include = "object").columns.tolist()
num_cols = df.select_dtypes(include = np.number).columns.drop(target).tolist()
df = feat_engg(df, num_cols, cat_cols)

print(num_cols)
print(cat_cols)

['employee_id', 'no_of_trainings', 'age', 'previous_year_rating', 'length_of_service', 'KPIs_met >80%', 'awards_won?', 'avg_training_score']
['department', 'region', 'education', 'gender', 'recruitment_channel']

/var/folders/y5/lf_stmcj5nv2hnzy3q1b5pb80000gn/T/ipykernel_2761/2691528503.py:29: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  cat_cols = df.select_dtypes(include = "object").columns.tolist()

In [11]:
print(cat_cols)

['department', 'region', 'education', 'gender', 'recruitment_channel']

In [12]:
df["department"].value_counts()

department
Sales & Marketing    16840
Operations           11348
Technology            7138
Procurement           7138
Analytics             5352
Finance               2536
HR                    2418
Legal                 1039
R&D                    999
Name: count, dtype: int64

In [13]:
values = df["region"].value_counts()
print(values)
for i in values.index:
    print(i)

region
region_2     12343
region_22     6428
region_7      4843
region_15     2808
region_13     2648
region_26     2260
region_31     1935
region_4      1703
region_27     1659
region_16     1465
region_28     1318
region_11     1315
region_23     1175
region_29      994
region_32      945
region_19      874
region_20      850
region_14      827
region_25      819
region_17      796
region_5       766
region_6       690
region_30      657
region_8       655
region_10      648
region_1       610
region_24      508
region_12      500
region_9       420
region_21      411
region_3       346
region_34      292
region_33      269
region_18       31
Name: count, dtype: int64
region_2
region_22
region_7
region_15
region_13
region_26
region_31
region_4
region_27
region_16
region_28
region_11
region_23
region_29
region_32
region_19
region_20
region_14
region_25
region_17
region_5
region_6
region_30
region_8
region_10
region_1
region_24
region_12
region_9
region_21
region_3
region_34
region_33
region_18

In [14]:
# def transform(df,cat_cols):

#     final_dict = {}

#     for col in cat_cols:

#         values = df[col].value_counts()

#         count = len(values)

#         transform_dict = {}

#         i = count

#         for i in values.index:

#             transform_dict[i] = count
#             count -=1

#         df[col] = df[col].map(transform_dict)

#         final_dict[col] = transform_dict

#         # print(col)
#         # print(values)
#         # print(values.index)

#     return final_dict

# # final_dict = transform(df,cat_cols)
# print(final_dict)

In [15]:
# a = df["region"].value_counts()

# a.rank(method= "dense", ascending= True).astype(int).to_dict()

In [16]:
def frequency_rank(df, cat_cols):
    for col in cat_cols:
        values = df[col].value_counts()
        mapping = values.rank(method="dense", ascending=True).astype(int).to_dict()
        df[col] = df[col].map(mapping)

    return df

In [17]:
cat_cols.remove("gender")

df = frequency_rank(df, cat_cols)

In [18]:
df.head()

   employee_id  department  ...  avg_training_score  is_promoted
0        65438           8  ...                  49            0
1        65141           7  ...                  60            0
2         7513           8  ...                  50            0
3         2542           8  ...                  50            0
4        48945           6  ...                  73            0

[5 rows x 14 columns]

In [19]:
df = pd.get_dummies(
    df,
    columns= ["gender"],
    dtype= int
)

In [20]:
from sklearn.model_selection import train_test_split

X = df.drop("is_promoted",axis= 1)
y = df["is_promoted"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

In [21]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()

model.fit(X_train, y_train)

/Users/theerdhasjoy/BIA/bia_py_env/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [22]:
# predict using the trained model

y_pred = model.predict(X_test)

#  y_test and y_pred

predict_df = pd.DataFrame({'Actual' : y_test, 'Predicted' : y_pred})
predict_df.head(10)

       Actual  Predicted
40907       0          0
51939       0          0
6978        0          0
12814       0          0
22921       0          0
33215       0          0
4028        0          0
1390        0          0
20735       1          0
17224       0          0

In [23]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report

#  Calculate metrices

accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
classification_report(y_test, y_pred)

#  Create a DataFrame for the metrics

metrics_df = pd.DataFrame({
    'Metric' : ['Accuracy', 'Precision', 'Recall'],
    'Score' : [accuracy, precision, recall]
})

print(f" Accuracy is {accuracy}")
print(f" Precision is : {precision}")
print(f" Recall is : {recall}")

 Accuracy is 0.9164386060937785
 Precision is : 0.16666666666666666
 Recall is : 0.0022026431718061676

In [26]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.92      1.00      0.96     10054
           1       0.17      0.00      0.00       908

    accuracy                           0.92     10962
   macro avg       0.54      0.50      0.48     10962
weighted avg       0.86      0.92      0.88     10962

In [ ]:

y_test_pred = model.predict(X_test)
y_train_pred = model.predict(X_train)

print("Train Accuracy: ", accuracy_score(y_train, y_train_pred))
print("Train Precision: ", precision_score(y_train, y_train_pred))
print("Train Recall : ", recall_score(y_train, y_train_pred))
print("Train F1 Score : ", f1_score(y_train, y_train_pred))

print("*" * 40)

print("Test Accuracy: ", accuracy_score(y_test, y_test_pred))
print("Test Precision: ", precision_score(y_test, y_test_pred))
print("Test Recall : ", recall_score(y_test, y_test_pred))
print("Test F1 Score : ", f1_score(y_test, y_test_pred))

Train Accuracy:  0.9136979427997993
Train Precision:  0.26
Train Recall :  0.003457446808510638
Train F1 Score :  0.0068241469816272965
****************************************
Test Accuracy:  0.9164386060937785
Test Precision:  0.16666666666666666
Test Recall :  0.0022026431718061676
Test F1 Score :  0.004347826086956522